- name: Set Prompt
  ansible.builtin.shell: set-prompt sonarqube

- name: Add sonarqube user
  ansible.builtin.user:
    name: sonar

- name: Install Java
  ansible.builtin.dnf:
    name: java-17-openjdk
    state: installed

- name: Download Sonarqube
  ansible.builtin.unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.5.0.89998.zip
    dest: /opt
    remote_src: yes
  become_user: sonar





